"""empty message

Revision ID: a0423dea7ab5
Revises: 78b5e2fa1520
Create Date: 2021-11-02 02:29:33.144306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0423dea7ab5'
down_revision = '78b5e2fa1520'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'cid',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'cid',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
